# kubernetes backend deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-backend
  namespace: rest-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-backend
  template:
    metadata:
      labels:
        app: rest-backend
    spec:
      containers:
        - name: rest-backend
          image: saltocumulus/project2-backend:latest
          ports:
            - containerPort: 6001