# kubernetes frontend deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-frontend
  namespace: rest-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-frontend
  template:
    metadata:
      labels:
        app: rest-frontend
    spec:
      containers:
        - name: rest-frontend
          image: saltocumulus/project2-frontend:latest
          ports:
            - containerPort: 80
